AACCaptureScreen:
    name: 'ParentName'

    BoxLayout:
        orientation: 'vertical'
        padding: '100dp'
        pos_hint: {'y': .3}

        TextInput:
            size_hint_y: None
            height: '32dp'
            multiline: False
            hint_text: 'Parent Name'
            
    Button:
        size_hint_y: None
        height: '48dp'
        text: 'Next'
        on_release: app.go_next_screen()
