AACCaptureScreen:
    name: 'ParentEmail'

    BoxLayout:
        orientation: 'vertical'
        padding: '100dp'
        pos_hint: {'y': .3}

        TextInput:
            size_hint_y: None
            height: '32dp'
            multiline: False
            hint_text: 'someone@somewebsite.com'
    Button:
        size_hint_y: None
        height: '48dp'
        text: 'Next'
        on_release: app.go_next_screen()