AACCaptureScreen:
    name: 'ParentEmail'

    BoxLayout:
        orientation: 'vertical'
        padding: '100dp'
        pos_hint: {'y': .3}

        TextInput:
            size_hint_y: None
            height: '50dp'
            multiline: False
            hint_text: 'someone@somewebsite.com'
            font_size: 32

    Button:
        size_hint_y: None
        height: '100dp'
        text: 'Next'
        font_size: 40
        on_release: app.go_next_screen()